[project]
name = "test"
version = "0.1.0"
description = "Streamlit app deployment"
authors = [{ name = "Rajesh MS" }]
dependencies = [
  "streamlit",
  "pandas",
  "numpy",
  "scikit-learn",
  "requests"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
